const data = [
    {
        "orderId": "14523",
        "userId": 11111,
        "michaelsOrderId": null,
        "productSubTotal": null,
        "productTotal": null,
        "orderTotal": 110,
        "orderType": 1,
        "shippingTotal": null,
        "taxTotal": null,
        "currency": null,
        "adjustedMerchandizeTotalTax": null,
        "adjustedShippingTotalTax": null,
        "shippingTotalTax": null,
        "merchandizeTotalTax": null,
        "orderToken": null,
        "storeId": null,
        "zipCode": null,
        "shippingStatus": null,
        "createdTime": "2020-12-10T18:58:45Z",
        "taxation": null,
        "email": null,
        "status": "Order Shipped",
        "orderItems": [
            {
                "itemId": 45,
                "orderId": "14523",
                "sellerStoreId": null,
                "thumbnail": null,
                "productId": null,
                "scheduleId": null,
                "michaelsProductId": null,
                "productName": "Item1",
                "quantity": 2,
                "basePrice": 55,
                "price": 110,
                "priceAfterItemDiscount": null,
                "priceAfterOrderDiscount": null,
                "adjustedTax": null,
                "tax": null,
                "taxBasis": null,
                "taxRate": null,
                "productType": null,
                "gift": null,
                "giftMessage": null,
                "itemDescription": "Explore the artist in you with this coloring poster from RoseArt.",
                "createdTime": null
            }
        ]
    },
    {
        "orderId": "13980",
        "userId": 11111,
        "michaelsOrderId": null,
        "productSubTotal": null,
        "productTotal": null,
        "orderTotal": 115,
        "orderType": 1,
        "shippingTotal": null,
        "taxTotal": null,
        "currency": null,
        "adjustedMerchandizeTotalTax": null,
        "adjustedShippingTotalTax": null,
        "shippingTotalTax": null,
        "merchandizeTotalTax": null,
        "orderToken": null,
        "storeId": null,
        "zipCode": null,
        "shippingStatus": null,
        "createdTime": "2020-12-14T13:10:24Z",
        "taxation": null,
        "email": null,
        "status": "Order Shipped",
        "orderItems": [
            {
                "itemId": 89,
                "orderId": "13980",
                "sellerStoreId": null,
                "thumbnail": null,
                "productId": null,
                "scheduleId": null,
                "michaelsProductId": null,
                "productName": "Item5",
                "quantity": 1,
                "basePrice": 115,
                "price": 115,
                "priceAfterItemDiscount": null,
                "priceAfterOrderDiscount": null,
                "adjustedTax": null,
                "tax": null,
                "taxBasis": null,
                "taxRate": null,
                "productType": null,
                "gift": null,
                "giftMessage": null,
                "itemDescription": "These neon crayons from Crayola are sure to add vibrancy to your art projects for that extra 'Wow' factor.",
                "createdTime": null
            }
        ]
    }
];
export default data;
